### ISSUE TITLE
Exit early from GeneralTree traversal methods

### ISSUE THREAD

**Issue by bretthysuik** [ngenerics/ngenerics#29]
Unless I'm missing something, there doesn't appear to be any way to exit the the traversal methods in `GeneralTree`. In some situations it's a waste of time to continue traversing the tree after the necessary condition is met. This doesn't work because the traversal implementations don't check `visitor.HasCompleted` in order to exit early, and the methods aren't virtual so they can't be overridden.

**Comment by rhanekom** [comment]
Patched with 1.5.1.
