### ISSUE TITLE
Wrong cross product of two Vector2D

### ISSUE THREAD

**Issue by subchannel13** [ngenerics/ngenerics#31]
Noticed that Vector2D.CrossProduct(Vector2D vector) returns null vector (zero length, not C# null) if left hand operand has Y = 0. After inspecting code, it turns out there is typo in function, it subtracts Y * vector.Y instead of Y * vector.X.

**Comment by rhanekom** [comment]
Thanks for reporting this.  I'll have a  look a this as soon as I can.  There is some cruft to clean up first - will report back here when that's fixed.

**Comment by rhanekom** [comment]
Closed in 1.5.0.
