### ISSUE TITLE
Project is dead? How about letting it go?

### ISSUE THREAD

**Issue by evil-shrike** [ngenerics/ngenerics#32]
Hi!
The project seems to be abandoned as it's 5 years passed since last commit. 

Is there any chance that you may change the license from LGPS upon something some permissive (MIT)?
May be in such a case someone would continue to works on the lib and move it to dotnet core/standard...

**Comment by SimonCropp** [comment]
happy to move to MIT. 

also happy to add more people who want to take up the code and move it forward

**Comment by rhanekom** [comment]
License has been moved to MIT.  Thanks for the nudge @evil-shrike .
